source 'https://cdn.cocoapods.org/'
source 'git@github.com:agencyenterprise/point-specs.git'

platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'PointSDK-Capacitor' do
  capacitor_pods
  pod 'PointSDK', '~> 0.1.15'
end
